- id: dbt2looker-verify
  name: verify
  entry: dbt2looker --strict -s
  description: "verify that dbt models are compatible with Looker"
  language: python
  require_serial: false
  types_or: [sql]

- id: dbt2looker-gen
  name: generate
  entry: dbt2looker -s
  description: "generate Looker model files catalog and manifest"
  language: python
  require_serial: true
  types_or: [sql]
